# Generated by Django 5.2.17 on 2026-09-01 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.URLField(blank=True, help_text='Link to online resume, portfolio, or LinkedIn profile.', null=True)),
                ('resume_file', models.FileField(blank=True, help_text='Uploaded resume document (PDF/DOCX).', null=True, upload_to='resumes/%Y/%m/')),
                ('cover_letter', models.TextField(blank=True, help_text='Candidate cover letter or introduction.', null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='APPLIED', help_text='Application lifecycle status.', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status'], name='application_status_1508e0_idx'), models.Index(fields=['applied_at'], name='application_applied_06e426_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'candidate'), name='unique_candidate_job_application')],
            },
        ),
    ]
